/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Insertion.Sort;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static int[] sort(int[] arr){
      for (int i=1; i<arr.length; i++){
        int temp =arr[i];
        int j=i-1;
        while (j>=0 && temp<arr[j]){
          arr[j+1] = arr[j];
          j = j-1;
        }
        arr[j+1]=temp;
      }
      return arr;
    }
    public static void main(String[] args) {
      int arr[] = {8,4,23,42,16,15};
      System.out.println(Arrays.toString(sort(arr)));

    }
}
