/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {


    public static void main(String[] args) {

      Graph<String> graph = new Graph<>();
      graph.addNode("Tareq");
      graph.addNode("osaid");
      graph.addNode("mohammed");
      graph.addNode("rahaf");
      graph.addNode("doaa");
      graph.addNode("doaa");
      graph.addNode("T");
      graph.addNode("A");
      graph.addEdge("Tareq","osaid");
      graph.addEdge("T","A");
      graph.addEdge("T","T");
      graph.addEdge("Tareq","mohammed");
      System.out.println(graph.getNeighbors("T"));
      System.out.println(graph.getNodes());
      System.out.println(graph.size());

    }
}
