/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Insertion.Sort;

import com.sun.tools.javac.Main;
import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void emptyArrayTest() {
      int arr[] = {};
      App app = new App();

      assertEquals("[]",Arrays.toString(app.sort(arr)),"Should return empty array");
    }
  @Test void notEmptyArrayTest() {
    int arr[] = {5,6,1,2,4,9,7,8};
    App app = new App();

    assertEquals("[1, 2, 4, 5, 6, 7, 8, 9]",Arrays.toString(app.sort(arr)),"Should return the same array but sorted");
  }
}
