/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void  successfullyAddedNode() {
      Graph<String,Integer> graph = new Graph<>();
      graph.addNode("T");
      assertEquals(1,graph.size());

    }
    @Test void  successfullyAddedEdge (){
      Graph<String,Integer> graph = new Graph<>();
      graph.addNode("T");
      graph.addNode("A");
      graph.addEdge("T","A");
      assertEquals("[A]",graph.getNeighbors("T").toString());
    }
    @Test void nodesCanBeProperlyRetrievedFromTheGraph(){
      Graph<String,Integer> graph = new Graph<>();
      graph.addNode("T");
      graph.addNode("A");
      assertNotNull(graph.getNodes());
    }
  @Test void onlyOneNodeAndEdgeCanBeProperlyReturned(){
    Graph<String,Integer> graph = new Graph<>();
    graph.addNode("T");
    graph.addEdge("T","T");
    assertNotNull(graph.getNodes());
    assertEquals("[T]",graph.getNeighbors("T").toString());
  }
  @Test void sizeIsReturned (){
    Graph<String,Integer> graph = new Graph<>();
    graph.addNode("T");
    graph.addNode("A");
    assertEquals(2,graph.size());
  }
  @Test void emptyGraphProperlyReturnsNull(){
    Graph<String,Integer> graph = new Graph<>();
    assertNull(graph.getNodes());
  }
  //===========================challenge 36============================

  @Test void notExistedNodeInTheGraph(){
    Graph<String,Integer> graph = new Graph<>();
    graph.addNode("T");
    graph.addNode("A");
    graph.addEdge("T","A");
    assertNull(graph.breadthFirst("G"));
    }
  @Test void existedNodeInTheGraph(){
    Graph<String,Integer> graph = new Graph<>();
    graph.addNode("T");
    graph.addNode("A");
    graph.addEdge("T","A");

    assertEquals("[T, A]",graph.breadthFirst("T").toString());
  }

  //===========================challenge 37============================
  @Test void existingBathBetweenTwoNodes(){
    Graph<String,Integer> graph = new Graph<>();
    List<String> c = new ArrayList<>();
    graph.addNode("T");
    graph.addNode("A");
    c.add("T");
    c.add("A");
    graph.addEdge("T","A",10);
    assertEquals("True, $10",Graph.businessTrip(graph,c));
  }
  @Test void notExistingBathBetweenTwoNodes(){
    Graph<String,Integer> graph = new Graph<>();
    List<String> c = new ArrayList<>();
    graph.addNode("T");
    graph.addNode("A");
    c.add("T");
    c.add("A");
    assertEquals("False, $0",Graph.businessTrip(graph,c));
  }
  @Test void existingNodeDepthFirst(){
    Graph<String,Integer> graph = new Graph<>();
    List<String> c = new ArrayList<>();
    graph.addNode("T");
    graph.addNode("A");
    c.add("T");
    c.add("A");
    graph.addEdge("T","A",10);
    assertEquals("[T, A]",graph.depthFirst("T").toString());
  }
  @Test void notExistingNodeDepthFirst(){
    Graph<String,Integer> graph = new Graph<>();
    graph.addNode("T");
    graph.addNode("A");
    graph.addEdge("T","A");
    assertNull(graph.depthFirst("G"));
  }
}
