/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashTable;

public class App {


    public static void main(String[] args) {
      HashTable<String,Integer> hashTable = new HashTable<>();
      hashTable.add("Tareq",50);
      hashTable.add("Mohammed",60);
      hashTable.add("Hatem",40);
//      hashTable.add("Oside",55);
//      hashTable.add("Rahaf",45);
//      hashTable.add("Doaa",65);
//      hashTable.add("Anas",46);
      hashTable.add("Teheran",46);
      hashTable.add("Siblings",47);
      System.out.println(hashTable);
      System.out.println("++++==============================+++++");
      System.out.println("++++==============================+++++");
      System.out.println(hashTable.get("Tareq"));
      System.out.println(hashTable.get("Mohammed"));
      System.out.println(hashTable.get("Omar"));
      System.out.println("++++==============================+++++");
      System.out.println("++++==============================+++++");
      System.out.println(hashTable.contain("Anas"));
      System.out.println(hashTable.contain("Omar"));
      System.out.println("++++==============================+++++");
      System.out.println("++++==============================+++++");
      System.out.println(hashTable.getBucketIndex("Tareq"));
      System.out.println(hashTable.getBucketIndex("Teheran"));
      System.out.println(hashTable.getBucketIndex("Siblings"));
    }
}
