/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
//        System.out.println(new App().getGreeting());

    LinkedList linkedList = new LinkedList();
//    linkedList.insert("T");
//    linkedList.insert("A");
//    linkedList.insert("R");
//    linkedList.insert("I");
//    linkedList.insert("Q");
//    linkedList.append("2");
//    linkedList.insertBefore("2", "3");
//    linkedList.insertAfter("3", "4");
//    System.out.println(linkedList);
//    linkedList.delete("3");
//    System.out.println(linkedList);
//    System.out.println(linkedList.includes("H"));
//    System.out.println(linkedList.includes("T"));

    linkedList.append("Z");
    linkedList.append("A");
    linkedList.append("D");
    linkedList.append("H");
    linkedList.append("G");
    linkedList.insertAfter("G","R");
    System.out.println(linkedList);


  }
}
