/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
//        System.out.println(new App().getGreeting());

    LinkedList linkedList = new LinkedList();
    linkedList.insert("T");
    linkedList.insert("A");
    linkedList.insert("R");
    linkedList.insert("I");
    linkedList.insert("Q");
    linkedList.append("2");
    linkedList.insertBefore("2", "3");
    linkedList.insertAfter("3", "4");
    System.out.println(linkedList);
    linkedList.delete("3");
    System.out.println(linkedList);
    System.out.println(linkedList.includes("H"));
    System.out.println(linkedList.includes("T"));
    String str =linkedList.kthFromEnd(3);
    System.out.println(str);

    System.out.println("=================================================================================");
    System.out.println("=================================================================================");
    LinkedList list1=new LinkedList();
    LinkedList list2=new LinkedList();
    list1.append("1");
    list1.append("3");
    list1.append("2");
    list1.append("8");
    list1.append("10");
    list1.append("11");
    list1.append("12");
    list1.append("13");
    System.out.println(list1);
    list2.append("5");
    list2.append("9");
    list2.append("4");
    list2.append("6");
    list2.append("7");
    list2.append("10");
    System.out.println(list2);
    LinkedList zip=new LinkedList();

    System.out.println(zip.zipLists(list1,list2));
  }
}
