/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
//        System.out.println(new App().getGreeting());

    LinkedList linkedList = new LinkedList();
    linkedList.insert("T");
    linkedList.insert("A");
    linkedList.insert("R");
    linkedList.insert("I");
    linkedList.insert("Q");
    System.out.println(linkedList);
    System.out.println(linkedList.includes("H"));
    System.out.println(linkedList.includes("T"));


  }
}
