/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
      BinarySearchTree<String> binarySearchTree = new BinarySearchTree<>();
      binarySearchTree.add("30");
      binarySearchTree.add("52");
      binarySearchTree.add("63");
      binarySearchTree.add("47");
      binarySearchTree.add("6");
      binarySearchTree.add("92");
      binarySearchTree.add("3");
      System.out.println(binarySearchTree.contains("7"));
      System.out.println(binarySearchTree.contains("52"));
      System.out.println(binarySearchTree.contains("30"));

    }
}
