/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import trees.KAryTree.KAryTree;

import java.util.ArrayList;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
      BinarySearchTree<Integer> binarySearchTree = new BinarySearchTree<>();
      binarySearchTree.add(30);
      binarySearchTree.add(52);
      binarySearchTree.add(63);
      binarySearchTree.add(47);
      binarySearchTree.add(6);
      binarySearchTree.add(92);
      binarySearchTree.add(3);
      System.out.println(binarySearchTree.contains(7));
      System.out.println(binarySearchTree.contains(52));
      System.out.println(binarySearchTree.contains(30));
      System.out.println(binarySearchTree.findMax());
      //------------------------------------------------------
      BinarySearchTree<Integer> binarySearchTree1=new BinarySearchTree<>();
      binarySearchTree1.add(5);
      binarySearchTree1.add(4);
      binarySearchTree1.add(2);
      binarySearchTree1.add(1);
      binarySearchTree1.add(6);
      binarySearchTree1.add(7);
      binarySearchTree1.add(8);
      System.out.println(binarySearchTree1.findMax());
      System.out.println(binarySearchTree1.breadthFirst(binarySearchTree1));
      System.out.println("==========================================================");
      System.out.println("==========================================================");
      BinarySearchTree<Integer> b1 = new BinarySearchTree<>();
      b1.add(7);
      b1.add(6);
      b1.add(9);
      b1.add(4);
      b1.add(6);
      b1.add(8);
      b1.add(10);
      BinarySearchTree<Integer> b2 = new BinarySearchTree<>();
      b2.add(7);
      b2.add(6);
      b2.add(9);
      b2.add(4);
      b2.add(6);
      b2.add(8);
      b2.add(10);
      System.out.println(b1.ComparingTwoDirectories(b1,b2));
      System.out.println("==========================================================");
      System.out.println("==========================================================");
      List<Integer> list = new ArrayList<>();
      list.add(1);
      list.add(2);
      list.add(3);
      list.add(4);
      list.add(5);
      list.add(6);
      list.add(7);
      list.add(8);
      list.add(9);
      list.add(30);
      KAryTree<Integer> kAryTree = new KAryTree<>(list, 3);
      kAryTree.postorder(kAryTree.getRoot());
      System.out.println();
      kAryTree.treeFizzBuzz();
      kAryTree.postorder(kAryTree.getRoot());
    }
}
